### ISSUE TITLE
Migration of old data

### ISSUE THREAD

**Issue by mzgajner** [RadioStudent/picapica#2]
The old data needs to be migrated to the new database along with the results of the gamified artist name matching/correcting.

**Comment by kokoon** [comment]
What's done so far:

- artists (including "votefix" - the gamified artist name correcting)
  - name
  - albums
  - related artists (these include name corrections and aliases)
- albums
  - artists
  - tracks
  - date (the dates were *really* poorly formatted in the old database, this needs some more work, maybe another game)
- tracks
  - track number
  - title
  - album
  - duration
  - genres
  - languages

**Comment by mzgajner** [comment]
More than enough for the milestone.
