### ISSUE TITLE
Don't use dots in object keys in API

### ISSUE THREAD

**Issue by mzgajner** [RadioStudent/picapica#31]
Example - when using the API to search, returned results are track objects with keys such as `artist.name` and `album.name`. This is a bit inconvenient, since you have to refer to them using `tracks['artist.name']` notation. If possible, change this to the more conventional camelCase, so that we may use dot notation.

**Comment by kokoon** [comment]
We can easily change this, since elastica results (that is the origin of the notation in question) get remapped anyway. But what about search parameters? We probably want the input keys to match output.

**Comment by zeljkomiklos** [comment]
Hura! 

:D 

2015-03-14 11:47, je Jure Žitnik napisal 

> Closed #31 [1]. 
> 
> --
> Reply to this email directly or view it on GitHub [2].

-- 
Vodja izvedbe programa RŠ
 

Links:
------
[1] https://github.com/RadioStudent/picapica/issues/31
[2] https://github.com/RadioStudent/picapica/issues/31#event-253485680

**Comment by kokoon** [comment]
;)
