### ISSUE TITLE
Single playlist editor

### ISSUE THREAD

**Issue by mzgajner** [RadioStudent/picapica#8]
This view is the second step of the playlist editor.

User can access a form that consists of several parts:
- basic playlist info like date, time, title etc. (time selection is based on standard time slots)
- list of tracks that can be added, removed, reordered and commented (to provide insights for technicians and announcers)
- length of entire playlist and progress information (based on date and time we can suggest a required length)
- buttons for saving, printing, and finishing the playlist (the latter publishes the playlist to the website and generally marks it as complete)

Tracks are generally added from the track search.

Besides the explicit saving performed by user, the playlist is also auto saved periodically.

**Comment by g1smo** [comment]
This one is also done.
