### ISSUE TITLE
Release editor

### ISSUE THREAD

**Issue by mzgajner** [RadioStudent/picapica#9]
The release editor is primarely only used by the record library manager and is unavailable to regular users.

User can create a new release by filling in a two-part form:
- The first part of the form consists of fields that have a relation to the entire release (album title, label, year published, ...).
- The second part is a list of tracks with repeated groups of fields that have a relation to single tracks (artist, title, duration, ...).

Apart from manual data input, the user can also fill the form by importing external library data.

To edit existing release information, the user must perform a search and select any track from the album. By selecting the option to edit it, the entire release is opened for editing in above interface.

**Comment by g1smo** [comment]
WIP done. New releases can be put into picapica, editing needs to be added.
